### ISSUE TITLE
Just flashed using the TKG Toolkit and not working at all

### ISSUE THREAD

**Issue by dperkinsjr** [BNCaps/QMK-RGB#1]
I'm going to do my best to describe what's happening with the board after flashing your version of the Satan firmware. Press Enter, I get Shift + Q; press ;, and I get Ctrl + Alt + Select; press L and it does Shift + Win. The list goes on and on with crazy key combos coming out of nowhere. There isn't any soldering issues, I checked, nothing is getting crossed. Some keys are just not doing anything too. RGB works great, it's glowing right now, I just can't control it. I literally have no idea what to do, trying other firmwares seem to be resulting in all kinds of wildly different behavior, seeking help.

**Comment by BNCaps** [comment]
What PCB are you using, be aware there are mutiple versions of the Satan PCB. Post the listing where you got it. Or with decent pic of the back i could tell you

**Comment by dperkinsjr** [comment]
Satan GH60, I believe the newest edition of that. As I've researched apparently there is a 2016 version. This is an image of the one I'm using, but not where I bought it from.  https://ae01.alicdn.com/kf/HTB1I.PZKpXXXXXcXFXXq6xXFXXXv/Satan-GH60-PCB-White-Board-Flashed-Firmware-DIY-Mechanical-Keyboard-Poker-2-Pure-HHKB-with-Diode.jpg

**Comment by BNCaps** [comment]
Post a pic of the back of the PCB please. Thats the only way to tell the version. There are about 4 revisions of this PCB made by completely different people. This firmware was designed for the very very first version of the PCB (from Dec. 2015)  and has not been updated or anything sense.

This firmware was designed to be compiled with winavr and uploaded with FLIP.
FLIP : http://www.atmel.com/tools/flip.aspx 
winavr: https://sourceforge.net/projects/winavr/

**Comment by dperkinsjr** [comment]
Here's the image of my pcb, sorry I'm not entirely sure of everything since it's a board I snagged off the mech market. http://imgur.com/GfNfSfz

**Comment by BNCaps** [comment]
I mean, it looks like the correct PCB for this firmware. The key layout in the satan folder here is for a ver specific layout though, so you may want to look at that. Did the keyboard ever work or did you just assemble it?

**Comment by dperkinsjr** [comment]
My keymap definitely doesn't match yours so that's a start. What's the best way to go about editing it to match my layout. Specifically mine is basically a pok3r layout.

**Comment by dperkinsjr** [comment]
Getting help from someone else, thanks for the try. Good job on the firmware as the problem definitely is all on me.
